public class SkaterGame{
  public int dateYear;
  public int dateMonth;
  public int dateDay;
  public int gameNumber;
  public int ageYear;
  public int ageDay;
  public String team;
  public String opponent;
  public char outcome;
  public int goals;
  public int assists;
  public int points;
  public int plusMinus;
  public int penaltiesInMinutes;
  public int evenStrengthGoals;
  public int powerPlayGoals;
  public int shortHandedGoals;
  public int gameWinningGoals;
  public int evenStrenghtAssists;
  public int powerPlayAssists;
  public int shortHandedAssists;
  public int shotsOnGoal;
  public double shootingPercentage;
  public int shifts;
  public int timeOnIce;
  public int hits;
  public int blocks;
  public int faceOffWins;
  public int faceOffLosses;
  public double faceOffPercentage;

}
